### PR TITLE
Feature/multiple_inputs_outputs

### LINKED ISSUE #629: Support multi input and output
Right now, it's not possible to:
- Have a Module multiple inputs (eg. forward(x1, x2)).
- Have a Module with multiple outputs (returning a tuple).

I worked around the first problem by creating a Module with a single input and indexing each individual input.
But the second problem makes it impossible to use the TripletMarginLoss, for example, since it expects 3 outputs from the Module.

### PR DESCRIPTION
**Pull request by fernandocamargoti**
* Support Modules with multiple inputs and multiple outputs

Closes #629

### CODE REVIEW

**Comment by fernandocamargoti** [comment]
@MattPainter01, wait a little more, please. I just found an error and I'm gonna fix it.

**Comment by fernandocamargoti** [comment]
Ready, @MattPainter01. There was a problem when concatenating y_pred and y_true to create the loss_function_params when one of them (usually y_pred) was a tuple. So, I made sure _get_param_list() always returns a list.

**Comment by fernandocamargoti** [comment]
@MattPainter01, I found another problem during validation.

**Comment by fernandocamargoti** [comment]
@MattPainter01, now everything is ok. I'm training a triplet model and both train and validation steps worked fine.

**Comment by MattPainter01** [comment]
Great, thanks for your work! I'll merge it now.

**Pull request merged**
